eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
okta:
  oauth2:
    issuer: https://dev-15585796.okta.com/oauth2/default
    audience: api://default
spring:
  zipkin:
    baseUrl: http://localhost:9411
  security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://dev-0nrrcude14pccq4i.us.auth0.com/
